[package]

name = "itertools"
version = "0.3.0"

license = "MIT/Apache-2.0"
repository = "https://github.com/bluss/rust-itertools"
documentation = "http://bluss.github.io/rust-itertools/"
authors = ["bluss"]

description = "Extra iterator adaptors, iterator methods and macros."

keywords = ["iterator", "data-structure", "zip", "product"]

[dependencies.quickcheck]
optional = true
[dependencies.quickcheck_macros]
optional = true

[features]

unstable = []
qc = ["quickcheck", "quickcheck_macros"]
